# Generated by Django 3.1.2 on 2020-12-21 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='color',
            field=models.CharField(choices=[('', 'Color'), ('RD', 'Red'), ('WH', 'White'), ('RS', 'Rosé')], default='RD', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='style',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='taste_notes',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='img_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='logo_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='zipcode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.TextField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
