# Generated by Django 3.1.2 on 2020-12-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_winery_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('lat', models.IntegerField(max_length=100)),
                ('lon', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='winery',
            name='state',
        ),
        migrations.AlterField(
            model_name='winery',
            name='zipcode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='winery',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.county'),
        ),
    ]
