# Generated by Django 3.1.2 on 2020-12-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201221_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='wine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.wine'),
            preserve_default=False,
        ),
    ]
