# Generated by Django 3.1.2 on 2020-12-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201216_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='county',
            name='lon',
            field=models.IntegerField(),
        ),
    ]
