# Generated by Django 3.1.2 on 2020-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201216_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='county',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
