# Generated by Django 3.1.2 on 2020-12-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201217_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='winery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.winery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='winery',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.county'),
        ),
    ]
