# Generated by Django 3.1.2 on 2020-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201217_0729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='varietal',
            new_name='grape',
        ),
        migrations.AlterField(
            model_name='wine',
            name='color',
            field=models.CharField(choices=[('RD', 'Red'), ('WH', 'White'), ('RS', 'Rosé')], default='RD', max_length=5),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.CharField(max_length=4),
        ),
    ]
