# Generated by Django 3.1.2 on 2020-12-18 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_glossary_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Glossary',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
